# Generated by Django 4.1.3 on 2022-11-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=60)),
                ('login', models.CharField(max_length=45)),
                ('haslo', models.CharField(max_length=45)),
                ('adres', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Towar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ilosc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sklep.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Platnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sklep.zamowienie')),
            ],
        ),
        migrations.CreateModel(
            name='Koszyk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('towar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sklep.towar')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sklep.zamowienie')),
            ],
        ),
    ]
